### ISSUE TITLE
install.md not found

### ISSUE THREAD

**Issue by sacredland** [empus/armour#2] opened 2020-01-29 01:37 UTC
"Please refer to the separate file '***INSTALL.md***' for instructions on initial setup."

Currently, there is no INSTALL.md at all in the rep, only README.md and UPDATING.md

**Comment by empus** [comment] 2020-01-31 02:21
Yeah I know, this file doesn't exist yet unfortunately.  Hopefully I'll write some basic instructions soon!

**Comment by empus** [comment] 2020-02-02 17:04
Duplicate of #4

**Closed by empus** 2020-02-02 17:04 UTC
